channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.22.3
  - matplotlib=3.5.2
  - scipy=1.8.0
  - astropy=5.0.4
  - pip=22.0.4
  - pip:
      - tensorflow-probability==0.16.0
      - jax==0.3.10
      - jaxlib==0.3.10
      - numpyro==0.9.2
      - numpyro-ncx2==0.0.3
